import 'package:get/get.dart';
import 'package:zet_health/Helper/AppConstants.dart';

class StringHelper extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {

    'en_US': {
      "app_name": "Zet Health",
      "health": "Health",
      "book_now": "Book Now",
      "view_cart": "View Cart",
      "add_to_cart": "Add To Cart",
      "remove_from_cart": "Remove From Cart",
      "booking_at": "Booking at",
      "search_test": "Search Test",
      "select_lab": "Select Lab",
      "add_more_test": "Add more Test",
      "search_lab": "Search Lab...",
      "search_profile": "Search Profile...",
      "search_packages": "Search Packages...",
      "my_cart": "My Cart",
      "choose_slot": "Choose slot",
      "date": "Date",
      "time": "Time",
      "select_date": "Select Date",
      "select_time": "Select Time",
      "patient": "Patient",
      "address": "Address",
      "select_add_patient": "Select / Add Patient",
      "select_add_address": "Select / Add Address",
      "select_state": "Select State",
      "need_only_women_phlebo": "Need only Women Phlebo",
      "discount_applied": "Discount Applied",
      "remove": "Remove",
      "total_amount": "Total Amount :",
      "collection_charges": "Collection Charges :",
      "payable_amount": "Payable Amount :",
      "add_patient": "Add Patient",
      "add_address": "Add Address",
      "name": "Name",
      "enter_first_name": "Enter First Name",
      "enter_last_name": "Enter Last Name",
      "enter_name": "Enter Name",
      "first_name": "First Name",
      "last_name": "Last Name",
      "number": "Number",
      "email": "Email",
      "enter_number": "Enter Number",
      "enter_email": "Enter Email",
      "enter_address": "Enter Address",
      "complete_address": "Complete Address",
      "dob": "DOB",
      "select_dob": "Select DOB",
      "gender": "Gender",
      "relation": "Relation",
      "male": "Male",
      "female": "Female",
      "other": "Other",
      "save_changes": "Save Changes",
      "no_package_found": "No Package Found",
      "no_test_found": "No Test Found",
      "no_lab_found": "No Lab Found",
      "no_booking_found": "No Booking Found",
      "no_notification_found": "No Notification Found",
      "no_profile_found": "No Profile Found",
      "no_offer_found": "No Offer Found",
      "no_report_found": "No Report Found",
      "no_order_found": "No Order Found",
      "no_data_found": "No Data Found",
      "no_file_found": "No File Found",
      "no_prescription_found": "No Prescription Found",
      "you_can_select_multiple_test": "You can select Multiple Test",
      "we_assist_you_in_lab_test_booking": "We’ll assist you in lab tests booking.",
      "search_by_test": "Search By Test",
      "search_by_lab": "Search By Lab",
      "search_by_upload_prescription": "Search By Upload a\nPrescription",
      "search_for_tests_and_packages": "Search for Tests and Packages",
      "find_lab": "Find Lab",
      "notifications": "Notifications",
      "house_flat_blockno": "House / Flat / Block no.",
      "enter_house_flat_blockno": "Enter House / Flat / Block no.",
      "nearby_landmark": "Nearby Landmark",
      "enter_landmark": "Enter Landmark",
      "area": "Area",
      "enter_area": "Enter Area",
      "pincode": "Pincode",
      "enter_pincode": "Enter Pincode",
      "please_select_tests": "Please Select Tests",
      "fasting_not_required": "Fasting is Not Required",
      "fasting_required": "Fasting is Required",
      "search_country": "Search Country",
      "search_city": "Search City",
      "register": "REGISTER",
      "continue": "CONTINUE",
      "checkout_now": "Checkout Now",
      "msg_test_booked_success": "Your Test Booked Successfully. We will\nReach you on this Date and Time",
      "please_enter_first_name": "Please Enter First Name",
      "please_enter_last_name": "Please Enter Last Name",
      "please_enter_name": "Please Enter Name",
      "please_enter_email_address": "Please Enter Email Address",
      "please_enter_mobile_number": "Please Enter Mobile Number",
      "please_enter_valid_mobile_number": "Please Enter Valid Mobile Number",
      "please_enter_valid_email_address": "Please Enter Valid Email Address",
      "please_select_gender": "Please Select Gender",
      "please_select_date": "Please Select Date",
      "please_enter_pickup_address": "Please Enter Pickup Address",
      "please_enter_longitude": "Please Select Longitude",
      "please_enter_latitude": "Please Select Latitude",
      "please_select_patient": "Please Select Patient",
      "please_select_time_slot": "Please Select Time Slot",
      "confirm": "Confirm",
      "cancel": "Cancel",
      "go_to_my_appointment": "Go to My Appointment",
      "congratulation": "Congratulation!!",
      "select_time_slot": "Select Time Slot",
      "no_time_slot_found": "No Time Slot Found",
      "please_select_slot": "Please Select Slot",
      "confirm_time": "Confirm Time",
      "please_enter_otp": "Please Enter OTP",
      "please_enter_valid_otp": "Please Enter Valid OTP",
      "otp_invalid": "OTP is invalid",
      "my_bookings": "My Bookings",
      "cant_find_your_lab_test": "Can’t Find your lab Test?",
      "upload_prescription": "Upload Prescription",
      "popular_profiles": "Popular Profiles",
      "warning": "Warning",
      "msg_add_this_item_previously_added_test_will_removed": "Are you sure you want to add this item? Your previously added test will be removed.",
      "clear_local_cart_and_proceed": "Are you sure you want clear local cart and proceed.",
      "edit_my_profile": "Edit My Profile",
      "contact_us": "Contact Us",
      "order_history": "Order History",
      "subject": "Subject",
      "message": "Message",
      "submit": "Submit",
      "phone": "Phone",
      "reorder": "Reorder",
      "upload_profile_photo": "Upload Profile Photo",
      "change_profile_photo": "Change Profile Photo",
      "open_at": "Open at",
      "close_at": "Close at",
      "lab_detail": "Lab Detail",
      "code_copied": "Code Copied",
      "search_lifestyle_packages": "Search Lifestyle Packages",
      "msg_please_upload_prescription": "Please upload your prescription. You can either take a photo with your camera or choose an image from your gallery.",
      "share_app_message": "Download Now\nAndroid\n${AppConstants.playStoreURL}\nIOS\n${AppConstants.appStoreURL}",
      "clear_cart": "Clear Cart",
      "brows_file": "Brows File",
      "partner_with_us": "Partner With us",
      "select_city": "Select City",
      "address_list": "Address list",
      "pin_code": "Pin Code",
      "city": "City",
      "view_prescriptions": "View Prescriptions",
      "auto_fetch": "Auto Fetch",
      "select_location": "Select Location",
      "latitude": "Latitude",
      "longitude": "Longitude",
      "please_enter_address": "Please Enter Address",
      "please_enter_house_no": "Please Enter House No",
      "please_enter_landmark": "Please Enter Landmark",
      "please_enter_area": "Please Enter Area",
      "please_enter_pin_code": "Please Enter PinCode",
      "please_enter_valid_pin_code": "Please Enter Valid PinCode",
      "please_select_city": "Please Select City",
      "please_select_address": "Please Select Address",
      "family_members": "Family Members",
      "guest": "Guest",
      "coupon_discount": "Coupon Discount",
      "paid": "Paid",
      "pay_now": "Pay Now",
      "estimated": "Estimated",
      "delivery_time": "delivery time ",
      "pickup_time": "pickup time ",
      "order_cancel": "Order Cancelled",
      "order_complete": "Order Completed",
      "order_history_detail": "Order History Detail",
      "patient_name": "Patient Name",
      "patient_address": "Patient Address",
      "total_payable_amount": "Total Payable Amount",
      "add_review" : "Add Review",
      "write_review_here" : "Write your review here...",
      "rating" : "Rating",
      "review" : "Review",
      "please_write_review" : "Please write your review",
      "submit_review" : "Submit Review",
      "rate_your_experience" : "Rate your experience",
      "no_review_found" : "No Review Found Yet!",
      "rating_and_reviews" : "Rating & Reviews",
      "please_add_your_review" : "Please add an your review.",
      "reviews_ratings" : "Reviews & Ratings",
      "item_added_to_cart" : "Item added to cart",
      "item_removed_from_cart" : "Item removed from cart",
      "search" : "Search",
      "test" : "Test",
      "package" : "Package",
      "profile" : "Profile",
      "included_test" : "Included Test",
      "included_test_profile" : "Included Test & Profile",
      "delete_account" : "Delete Account",
      "please_confirm_account_deletion" : "Please confirm account deletion",
      "please_select_star" : "Please select star",
      "yes" : "Yes",
      "no" : "No",
      "update" : "Update",
      "address_type" : "Address Type",
      "spouse_to_be_added_list" : '"Spouse" to be added in the list',
      "delete_address" : 'Are you sure you want to delete address ?',
      "delete_family_member" : 'Are you sure you want to delete family member ?',
      "upload_prescription_description" : 'Please Upload your prescription from the home screen to view all prescriptions here.',
      "no_member_added_yet" : 'No member added yet',
      "no_address_added_yet" : 'Your address book is empty.',
      "no_address_added_yet_description" : 'Add your preferred delivery address or use current location to enable us to provide better service.',
      "no_address_added_yet_but_current" : 'No saved addresses yet.',
      "no_address_added_yet_description_but_current" : 'Add a delivery address to make checkout faster and never lose it when you switch devices.',
      "add_new_member" : 'Add new member',
      "add_new_address" : 'Add new address',
      "wallet_history" : 'Wallet History',
      "no_transaction_found" : 'No Transaction Found',
      "did_not_receive_otp": "Didn't receive the OTP?",
      "parameter_included": "Parameter Included",
      "parameters": "Parameters",
      "add_balance": "Add Balance",
      "balance": "Balance",
      "add_money_instantly": "Add Money Instantly",
      "get_instant_deposits_using_upi_or_netBanking": "Get Instant deposits using UPI or NetBanking",
      "add_balance_message": "Add Balance Anytime, Anywhere!",
      "add_balance_message_2": "Experience hassle-free and secure balance addition. We are committed to providing you with a secure and enjoyable experience.",
      "add_amount": "Add Amount",
      "please_enter_amount": "Please Enter Amount",
      "max_amount_message": "Maximum amount is 10,000",
      "selected_item_is_from_different_lab": "Selected item is from different lab. Are you sure you want to add this item?",
      "lab_name": "Lab Name",
      "users": "Users",
      "search_user": "Search User",
      "no_user_found": "No User Found",
      "login": "Log In",
      "my_account": "My Account",
      "change_patient" : "Change Patient",
      "change_address" : "Change Address",
      "changing_address_warning" : "Changing the address will remove all tests from cart. Do you want to proceed?",
    }
  };

}